apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
spec:
  ingressClassName: nginx
  rules:
  - host: "msproject.dev"
    http:
      paths:
      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: auth-srv
            port:
              number: 8000